import { Dnd5eLegacyTeleportPreserver } from "./Dnd5eLegacyTeleportPreserver.js";

/**
 * Reads dnd5e activity source for the legacy migration. Foundry cleans that
 * source against the schema of each activity type, and dnd5e 6 registers a
 * native `teleport`, so a legacy More Activities teleport arrives pruned there.
 * Its legacy fields come back from the copy kept by
 * {@link Dnd5eLegacyTeleportPreserver}.
 */
export class Dnd5eDataAdapter {
  /**
   * Returns a detached, id-keyed activity map from the document's source.
   * Test doubles that do not expose `_source` fall back to their serialized
   * document data.
   */
  static getRawActivityMap(item) {
    return Dnd5eDataAdapter.#toActivityMap(Dnd5eDataAdapter.#activitiesSource(item));
  }

  /** Returns the persisted activity container with its object/array shape intact. */
  static getRawActivities(item) {
    const activities = Dnd5eDataAdapter.clone(Dnd5eDataAdapter.#activitiesSource(item));
    if (Array.isArray(activities)) {
      return activities.map((activity) => Dnd5eLegacyTeleportPreserver.restore(activity));
    }
    if (!activities || typeof activities !== "object") {
      return activities;
    }
    return Object.fromEntries(Object.entries(activities)
      .map(([id, activity]) => [id, Dnd5eLegacyTeleportPreserver.restore(activity)]));
  }

  static clone(value) {
    if (value === undefined || value === null) {
      return value;
    }
    return JSON.parse(JSON.stringify(value));
  }

  /**
   * Activity ids generated by Foundry are path-safe. Restrict dotted updates
   * to that shape so a malformed legacy id cannot accidentally address a
   * sibling property. Callers can use a complete raw-map update as a fallback.
   */
  static canUpdateActivityIndividually(activityId) {
    return /^[A-Za-z0-9_-]+$/.test(String(activityId ?? ""));
  }

  static activityUpdate(activityId, activitySource) {
    if (!Dnd5eDataAdapter.canUpdateActivityIndividually(activityId)) {
      return null;
    }
    return {
      [`system.activities.${activityId}`]: Dnd5eDataAdapter.clone(activitySource)
    };
  }

  static activitiesUpdate(activityMap) {
    return { "system.activities": Dnd5eDataAdapter.clone(activityMap ?? {}) };
  }

  /**
   * Applies replacements to a raw container without changing whether dnd5e
   * stored activities as a keyed object or an array.
   */
  static replaceActivities(rawActivities, replacements) {
    const next = Dnd5eDataAdapter.clone(rawActivities ?? {});
    const replacementMap = replacements instanceof Map ? replacements : new Map(replacements ?? []);
    if (Array.isArray(next)) {
      return next.map((activity) => {
        const id = String(activity?._id ?? activity?.id ?? "").trim();
        return replacementMap.has(id) ? Dnd5eDataAdapter.clone(replacementMap.get(id)) : activity;
      });
    }
    if (!next || typeof next !== "object") {
      return {};
    }
    for (const [id, source] of replacementMap) {
      next[id] = Dnd5eDataAdapter.clone(source);
    }
    return next;
  }

  static #activitiesSource(item) {
    const rawSource = item?._source?.system;
    if (rawSource && Object.hasOwn(rawSource, "activities")) {
      return rawSource.activities;
    }

    const serialized = item?.toObject?.();
    if (serialized?.system && Object.hasOwn(serialized.system, "activities")) {
      return serialized.system.activities;
    }

    return item?.system?.activities ?? {};
  }

  static #detach(activity) {
    return Dnd5eLegacyTeleportPreserver.restore(Dnd5eDataAdapter.clone(activity));
  }

  static #toActivityMap(activities) {
    if (Array.isArray(activities)) {
      return Object.fromEntries(activities.flatMap((activity) => {
        const id = String(activity?._id ?? activity?.id ?? "").trim();
        // An array entry without an id cannot be addressed safely by Foundry's
        // embedded activity update syntax, so leave it outside migration scope.
        return id ? [[id, Dnd5eDataAdapter.#detach(activity)]] : [];
      }));
    }

    if (!activities || typeof activities !== "object") {
      return {};
    }

    return Object.fromEntries(Object.entries(activities)
      .filter(([, activity]) => activity && typeof activity === "object")
      .map(([id, activity]) => [id, Dnd5eDataAdapter.#detach(activity)]));
  }
}
